/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        surface: "var(--surface)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "on-surface": "var(--on-surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-surface-muted": "var(--on-surface-muted)",
        "on-surface-subtle": "var(--on-surface-subtle)",
        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",
        primary: "var(--primary)",
        "on-primary": "var(--on-primary)",
        secondary: "var(--secondary)",
        "on-secondary": "var(--on-secondary)",
        tertiary: "var(--tertiary)",
        error: "var(--error)",
        "signal-green": "var(--signal-green)",
        "signal-amber": "var(--signal-amber)",
        "signal-red": "var(--signal-red)",
        "signal-cyan": "var(--signal-cyan)",
        "signal-violet": "var(--signal-violet)",
        "accent-blue": "var(--accent-blue)",
        "accent-green": "var(--accent-green)",
        "accent-amber": "var(--accent-amber)",
        brand: {
          50:  "#f0f4ff",
          100: "#e0e9ff",
          300: "#93a8f8",
          400: "#7189f6",
          500: "#4f6ef7",
          600: "#3d5ce6",
          700: "#2d4bd4",
          900: "#1a2d8a",
        },
      },
      fontFamily: {
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
    },
  },
  plugins: [],
};
